version: 'version'
services:
  api:
    build: ./api
    container_name: E-Store
    ports:
      - '5000:5000'
    volumes:
      - ./api:/app
      - ./app/node_modules

  client:
    build: ./client
    container_name: client_c
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
            