# fly.toml app configuration file generated for estore-mm on 2024-01-26T14:53:03+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'estore-mm'
primary_region = 'ams'

[build]
  image = 'mahmoud2023/restore:latest'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
